[tool.black]
line-length = 100
verbose = 1
color = true
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.venv
  )/
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 100
src_paths = ["myutils", "tests"]
skip = [".mypy_cache", ".pytest_cache", ".venv"]

[tool.pylint.messages_control]
disable = "missing-docstring,logging-fstring-interpolation,too-few-public-methods,too-many-arguments,duplicate-code"

[tool.pylint.format]
max-line-length = "100"
indent-string = "    "
good-names = "db, i, j"

[tool.pylint.master]
ignore = ".venv, tests"
max-instance-attributes = 10
